# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(477, 338)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 231, 151))
        self.groupBox.setObjectName("groupBox")
        self.button_1_1 = QtWidgets.QPushButton(self.groupBox)
        self.button_1_1.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.button_1_1.setObjectName("button_1_1")
        self.button_1_2 = QtWidgets.QPushButton(self.groupBox)
        self.button_1_2.setGeometry(QtCore.QRect(20, 60, 71, 31))
        self.button_1_2.setObjectName("button_1_2")
        self.button_1_4 = QtWidgets.QPushButton(self.groupBox)
        self.button_1_4.setGeometry(QtCore.QRect(20, 100, 71, 31))
        self.button_1_4.setObjectName("button_1_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(110, 20, 101, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label.setObjectName("label")
        self.comboBox_1_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_1_3.setGeometry(QtCore.QRect(10, 30, 41, 16))
        self.comboBox_1_3.setObjectName("comboBox_1_3")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.comboBox_1_3.addItem("")
        self.button_1_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.button_1_3.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.button_1_3.setObjectName("button_1_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 190, 111, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.button_2_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.button_2_1.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.button_2_1.setObjectName("button_2_1")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(130, 190, 120, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.button_4_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.button_4_1.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.button_4_1.setObjectName("button_4_1")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(280, 20, 171, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(9, 20, 131, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.text_angle = QtWidgets.QTextEdit(self.groupBox_6)
        self.text_angle.setGeometry(QtCore.QRect(40, 20, 51, 21))
        self.text_angle.setObjectName("text_angle")
        self.text_scale = QtWidgets.QTextEdit(self.groupBox_6)
        self.text_scale.setGeometry(QtCore.QRect(40, 50, 51, 21))
        self.text_scale.setObjectName("text_scale")
        self.text_tx = QtWidgets.QTextEdit(self.groupBox_6)
        self.text_tx.setGeometry(QtCore.QRect(40, 80, 51, 21))
        self.text_tx.setObjectName("text_tx")
        self.text_ty = QtWidgets.QTextEdit(self.groupBox_6)
        self.text_ty.setGeometry(QtCore.QRect(40, 110, 51, 21))
        self.text_ty.setObjectName("text_ty")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 35, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 35, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 35, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 35, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(100, 20, 35, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(100, 80, 35, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(100, 110, 35, 16))
        self.label_10.setObjectName("label_10")
        self.button_3_1 = QtWidgets.QPushButton(self.groupBox_6)
        self.button_3_1.setGeometry(QtCore.QRect(10, 140, 121, 21))
        self.button_3_1.setObjectName("button_3_1")
        self.button_3_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.button_3_2.setGeometry(QtCore.QRect(20, 210, 121, 21))
        self.button_3_2.setObjectName("button_3_2")
        self.button_ok = QtWidgets.QPushButton(Dialog)
        self.button_ok.setGeometry(QtCore.QRect(280, 290, 71, 21))
        self.button_ok.setObjectName("button_ok")
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setGeometry(QtCore.QRect(370, 290, 71, 21))
        self.button_cancel.setObjectName("button_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "1. Carlibration"))
        self.button_1_1.setText(_translate("Dialog", "1.1 Find Corners"))
        self.button_1_2.setText(_translate("Dialog", "1.2 Intrinsic"))
        self.button_1_4.setText(_translate("Dialog", "1.4 Distortion"))
        self.groupBox_2.setTitle(_translate("Dialog", "1.3 Extrinsic"))
        self.label.setText(_translate("Dialog", "Select image"))
        self.comboBox_1_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_1_3.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_1_3.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_1_3.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_1_3.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_1_3.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_1_3.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_1_3.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_1_3.setItemText(8, _translate("Dialog", "9"))
        self.comboBox_1_3.setItemText(9, _translate("Dialog", "10"))
        self.comboBox_1_3.setItemText(10, _translate("Dialog", "11"))
        self.comboBox_1_3.setItemText(11, _translate("Dialog", "12"))
        self.comboBox_1_3.setItemText(12, _translate("Dialog", "13"))
        self.comboBox_1_3.setItemText(13, _translate("Dialog", "14"))
        self.comboBox_1_3.setItemText(14, _translate("Dialog", "15"))
        self.button_1_3.setText(_translate("Dialog", "1.3 Extrinsic"))
        self.groupBox_3.setTitle(_translate("Dialog", "2. Augmented Reality"))
        self.button_2_1.setText(_translate("Dialog", "2.1 Augmented Reality"))
        self.groupBox_4.setTitle(_translate("Dialog", "4. Find Contour"))
        self.button_4_1.setText(_translate("Dialog", "4.1 Find Contour"))
        self.groupBox_5.setTitle(_translate("Dialog", "3. Image Transformation"))
        self.groupBox_6.setTitle(_translate("Dialog", "3.1 Rot, Scale, Translate"))
        self.label_2.setText(_translate("Dialog", "Angle:"))
        self.label_3.setText(_translate("Dialog", "Scale:"))
        self.label_4.setText(_translate("Dialog", "Tx:"))
        self.label_5.setText(_translate("Dialog", "Ty:"))
        self.label_6.setText(_translate("Dialog", "deg"))
        self.label_9.setText(_translate("Dialog", "pixel"))
        self.label_10.setText(_translate("Dialog", "pixel"))
        self.button_3_1.setText(_translate("Dialog", "3.1 Rotation, scaling, translation"))
        self.button_3_2.setText(_translate("Dialog", "3.2 Perspective Transform"))
        self.button_ok.setText(_translate("Dialog", "OK"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))
